FROM debian:bookworm-slim

WORKDIR /nctl

RUN apt-get update && apt-get install -y --no-install-recommends \
		python3-pip \
		python3-setuptools \
		nftables \
		python3-nftables \
		iproute2

COPY requirements.txt /nctl/

RUN python3 -m pip install --no-cache-dir --break-system-packages -r /nctl/requirements.txt

COPY . /nctl

# We bind to 0.0.0.0 and the nft rules will forbid outside access.
# In the "production" Dockerfile, we do not need the --host parameter
# since "fastapi run" binds to 0.0.0.0 by default.
CMD ["fastapi", "dev", "main.py", "--host", "0.0.0.0", "--port", "6784"]
