FROM python:3.12-alpine3.19

WORKDIR /nctl

RUN apk add --no-cache nftables git \
	&& pip install 'git+https://git.netfilter.org/nftables@v1.1.0#egg=nftables&subdirectory=py' \
	&& apk del git

COPY requirements.txt /nctl/

RUN pip install -r /nctl/requirements.txt

COPY . /nctl

# We bind to 0.0.0.0 and the nft rules will forbid outside access.
# In the "production" Dockerfile, we do not need the --host parameter
# since "fastapi run" binds to 0.0.0.0 by default.
CMD ["fastapi", "dev", "main.py", "--host", "0.0.0.0", "--port", "6784"]