name: infra-langate-beta
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: langate/backend-beta
    environment:
      WEBSITE_HOST: beta.${WEBSITE_HOST}
      HTTP_PROTOCOL: ${PROTOCOL}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      PROXY_PORT: ${EXTERNAL_PROXY_PORT}
      STATIC_ROOT: ${BACKEND_STATIC_ROOT}
      MEDIA_ROOT: ${BACKEND_MEDIA_ROOT}
      SUPERUSER_USER: ${SUPERUSER_USER}
      SUPERUSER_PASS: ${SUPERUSER_PASS}
      DJANGO_SECRET: ${BACKEND_DJANGO_SECRET}
      SESSION_COOKIE_AGE: ${SESSION_COOKIE_AGE}
      DEV: ${DEV}
    volumes:
      - ./volumes/beta/backend:/app/v1
      - ./backend:/app
    expose:
      - 8000
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_SUPERUSER}
      POSTGRES_PASSWORD: ${DB_SUPERPASS}
      LANGATE_USERNAME: ${DB_USER}
      LANGATE_PASSWORD: ${DB_PASS}
      LANGATE_DATABASE: ${DB_NAME}
      TZ: Europe/Paris
      PGTZ: Europe/Paris
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
#      - ./volumes/beta/postgres/data:/var/lib/postgresql/data # TODO DO NOT COMMIT THIS
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: langate/frontend-beta
    environment:
      - VITE_API_URL=${PROTOCOL}://api.beta.${WEBSITE_HOST}
#      - NODE_ENV=${FRONTEND_NODE_ENV}
      - VITE_WEBSITE_HOST=beta.${WEBSITE_HOST}
      - VITE_SESSION_COOKIE_AGE=${SESSION_COOKIE_AGE}
    volumes:
      - ./frontend:/src
    expose:
      - "5173"
    networks:
      - backend

  caddy:
    image: caddy
    environment:
      - CADDY_HOST=beta.${WEBSITE_HOST}
      - CADDY_PORT=80
      - STATIC_ROOT=${BACKEND_STATIC_ROOT}
      - MEDIA_ROOT=${BACKEND_MEDIA_ROOT}
      - FRONTEND_PORT=5173
    ports:
      - "${PREPROD_PROXY_PORT}:80"
    volumes:
      - ./volumes/beta/backend:/srv/backend
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile
      - ./volumes/beta/caddy/data:/data
      - ./volumes/beta/caddy/config:/config
      - ./volumes/beta/caddy/logs:/var/log/caddy
    networks:
      - backend
    depends_on:
      - backend
      - frontend

  netcontrol:
    build:
      context: ./netcontrol
      dockerfile: Dockerfile.dev
    image: langate/netcontrol
    environment:
      - MOCK_NETWORK=${MOCK_NETWORK}
    cap_add:
      - NET_ADMIN
    volumes:
      - ${VARIABLES_PATH}:/variables.json
    network_mode: "host"

networks:
  backend:
