# Generated by Django 4.1.13 on 2025-03-03 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import langate.network.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mac', models.CharField(max_length=17, unique=True, validators=[langate.network.models.validate_mac])),
                ('whitelisted', models.BooleanField(default=False)),
                ('bypass', models.BooleanField(default=False)),
                ('mark', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='network.device')),
                ('ip', models.GenericIPAddressField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('network.device',),
        ),
    ]
